---
version: '3.7'
services:
  database:
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    image: mysql:5.7

  wordpress:
    build:
      args:
        WORDPRESS_IMAGE_TAG: ${WORDPRESS_IMAGE_TAG:-latest}
        MODERNITY: ${MODERNITY:-modern}
      context: wordpress-basic-authentication
    depends_on:
      - database
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      BASIC_AUTHENTICATION_USER_NAME: authuser
      BASIC_AUTHENTICATION_USER_PASSWORD: authpassword
    image: wordpress-basic-authentication:latest
    ports:
      - 80:80
    restart: always
    volumes:
      - ${PATH_TO_PLUGIN_DIRECTORY}:/var/www/html/wp-content/plugins
